export const servicesByType = {
  barber: [
    {
      id: 'classic-cut',
      name: 'Classic Cut',
      price: 25,
      priceLabel: '£25',
      duration: '45 min',
      description: 'Scissor or clipper cut shaped to your style, finished with product and a professional blow-dry.',
    },
    {
      id: 'skin-fade',
      name: 'Skin Fade',
      price: 30,
      priceLabel: '£30',
      duration: '50 min',
      description: 'Razor-sharp fade from skin up to your desired length. Seamless gradient, clean lines.',
    },
    {
      id: 'beard-trim',
      name: 'Beard Trim',
      price: 15,
      priceLabel: '£15',
      duration: '20 min',
      description: 'Shape, define and tame your beard. Includes hot towel and finishing balm.',
    },
    {
      id: 'hot-towel-shave',
      name: 'Hot Towel Shave',
      price: 35,
      priceLabel: '£35',
      duration: '45 min',
      description: 'Traditional straight-razor shave with pre-shave oil, hot towels, and premium aftershave.',
    },
    {
      id: 'combo',
      name: 'Cut & Beard Combo',
      price: 40,
      priceLabel: '£40',
      duration: '65 min',
      description: "Full haircut plus beard trim and shape — the complete gentleman's service.",
    },
    {
      id: 'kids-cut',
      name: "Kids Cut",
      price: 18,
      priceLabel: '£18',
      duration: '30 min',
      description: 'Gentle, patient service for little ones under 12. Same quality, smaller chair.',
    },
  ],
  hairdresser: [
    {
      id: 'cut-blow-dry',
      name: 'Cut & Blow Dry',
      price: 45,
      priceLabel: '£45',
      duration: '60 min',
      description: 'Precision cut tailored to your face shape and lifestyle, finished with a silky blow dry.',
    },
    {
      id: 'balayage',
      name: 'Balayage',
      price: 120,
      priceLabel: '£120',
      duration: '3 hrs',
      description: 'Hand-painted colour for a natural, sun-kissed gradient. Low maintenance, high impact.',
    },
    {
      id: 'highlights',
      name: 'Highlights',
      price: 95,
      priceLabel: '£95',
      duration: '2.5 hrs',
      description: 'Classic foil highlights to add dimension, brightness, and depth to your colour.',
    },
    {
      id: 'extensions',
      name: 'Extensions',
      price: 200,
      priceLabel: 'from £200',
      duration: 'Consultation',
      description: 'Add instant length and volume with our premium hair extension service. Bespoke consultation required.',
    },
    {
      id: 'keratin',
      name: 'Keratin Treatment',
      price: 150,
      priceLabel: '£150',
      duration: '3 hrs',
      description: 'Banish frizz and transform texture for up to three months. Leaves hair smooth and glossy.',
    },
  ],
};
